// Test with wrong credentials
POST http://localhost:8080/api/authentication/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@techtalsteve.com",
  "password": "pass"
}

###

// Test with right credentials
POST http://localhost:8080/api/authentication/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@techtalsteve.com",
  "password": "password"
}

###

// Test protected endpoint without token
GET http://localhost:8080/api/authentication/roles
Accept: application/json
Content-Type: application/json

###

// Test protected endpoint with right token
GET http://localhost:8080/api/authentication/roles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3RlY2h0YWxrc3RldmUuY29tL2lzc3VlciIsInVwbiI6ImFkbWluQHRlY2h0YWxzdGV2ZS5jb20iLCJncm91cHMiOlsiUk9MRV9BUFBMSUNBVElPTiJdLCJpYXQiOjE2Mjg0Mzg3ODgsImV4cCI6MTY1OTk3NDc4OCwianRpIjoiNmJmOGM3ZDktNDc5Yy00N2FhLWIyMTItYjIyNDhjZmU2NWMxIn0.PUSA4z6eXlBv73j6odS9HZayc2eNvSBgQ2fxb8e6XjL-EWt4aIsoPOIBZqgpe1Kqn5NB2tAFE8ny6NURI1I2uORbQjXJQRGW1Lv-tc7CbOEjel1ehYbLw29NiGYRrNwvyCRpPoutBL4rPnasi4mhTAnTJTTQyMvDP_0PC3s5B_9Gz0bkcrAnCYsDtFNCsVFSYNBMiRZ5wZWNRTqeiEZ1m9ofMyLXdMw-nZxxdLGzu5EhUPN3m9KGZrSxLaBNncugfmSA4ionwbglVcreohlR-_dKN2MDUu9Sak3watz4_jmgrgjZaVr89gGvdRH-z7vrgSMarh6mfPImPp4LhVTWxw
###